# Use the official Debian slim image for a lean base
FROM debian:12-slim

# Install necessary software like texlive-full and ghostscript
RUN apt-get update && apt-get install -y \
    texlive-full \
    ghostscript \
    rubber \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*