// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: tex_to_pdf.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // the name of the file (e.g. "main.tex")
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // the content of the file (e.g. "\documentclass{article}...")
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tex_to_pdf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_tex_to_pdf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_tex_to_pdf_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CompileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"` // A list of files. This allows sending TeX files and their corresponding images or other dependencies.
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tex_to_pdf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tex_to_pdf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_tex_to_pdf_proto_rawDescGZIP(), []int{1}
}

func (x *CompileRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type CompileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdfContent []byte `protobuf:"bytes,1,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"` // The content of the resulting PDF file
	Log        string `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`                                 // The log of the compilation process
}

func (x *CompileReply) Reset() {
	*x = CompileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tex_to_pdf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileReply) ProtoMessage() {}

func (x *CompileReply) ProtoReflect() protoreflect.Message {
	mi := &file_tex_to_pdf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileReply.ProtoReflect.Descriptor instead.
func (*CompileReply) Descriptor() ([]byte, []int) {
	return file_tex_to_pdf_proto_rawDescGZIP(), []int{2}
}

func (x *CompileReply) GetPdfContent() []byte {
	if x != nil {
		return x.PdfContent
	}
	return nil
}

func (x *CompileReply) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_tex_to_pdf_proto protoreflect.FileDescriptor

var file_tex_to_pdf_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x65, 0x78, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x64, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x78, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x64, 0x66, 0x22, 0x34,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x65, 0x78, 0x5f, 0x74, 0x6f, 0x5f, 0x70,
	0x64, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x41,
	0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x64, 0x66, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x64, 0x66, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f,
	0x67, 0x32, 0x53, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72,
	0x12, 0x44, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x50, 0x44, 0x46,
	0x12, 0x1a, 0x2e, 0x74, 0x65, 0x78, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x64, 0x66, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74,
	0x65, 0x78, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x64, 0x66, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6c, 0x73, 0x65, 0x69, 0x66, 0x66, 0x65, 0x72, 0x74,
	0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x74, 0x65, 0x78, 0x2d, 0x74, 0x6f, 0x2d, 0x70,
	0x64, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tex_to_pdf_proto_rawDescOnce sync.Once
	file_tex_to_pdf_proto_rawDescData = file_tex_to_pdf_proto_rawDesc
)

func file_tex_to_pdf_proto_rawDescGZIP() []byte {
	file_tex_to_pdf_proto_rawDescOnce.Do(func() {
		file_tex_to_pdf_proto_rawDescData = protoimpl.X.CompressGZIP(file_tex_to_pdf_proto_rawDescData)
	})
	return file_tex_to_pdf_proto_rawDescData
}

var file_tex_to_pdf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tex_to_pdf_proto_goTypes = []interface{}{
	(*File)(nil),           // 0: tex_to_pdf.File
	(*CompileRequest)(nil), // 1: tex_to_pdf.CompileRequest
	(*CompileReply)(nil),   // 2: tex_to_pdf.CompileReply
}
var file_tex_to_pdf_proto_depIdxs = []int32{
	0, // 0: tex_to_pdf.CompileRequest.files:type_name -> tex_to_pdf.File
	1, // 1: tex_to_pdf.TexCompiler.CompileToPDF:input_type -> tex_to_pdf.CompileRequest
	2, // 2: tex_to_pdf.TexCompiler.CompileToPDF:output_type -> tex_to_pdf.CompileReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tex_to_pdf_proto_init() }
func file_tex_to_pdf_proto_init() {
	if File_tex_to_pdf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tex_to_pdf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tex_to_pdf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tex_to_pdf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tex_to_pdf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tex_to_pdf_proto_goTypes,
		DependencyIndexes: file_tex_to_pdf_proto_depIdxs,
		MessageInfos:      file_tex_to_pdf_proto_msgTypes,
	}.Build()
	File_tex_to_pdf_proto = out.File
	file_tex_to_pdf_proto_rawDesc = nil
	file_tex_to_pdf_proto_goTypes = nil
	file_tex_to_pdf_proto_depIdxs = nil
}
